global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'article-service'
    static_configs:
      - targets: ['article-service:8080','happy-headlines-article-service-1:8080','happy-headlines-article-service-2:8080','happy-headlines-article-service-3:8080']
    metrics_path: /metrics

  - job_name: 'comment-service'
    static_configs:
      - targets: ['comment-service:8080','happy-headlines-comment-service-1:8080','happy-headlines-comment-service-2:8080']
    metrics_path: /metrics

  - job_name: 'publisher-service'
    static_configs:
      - targets: ['publisher-service:8080']
    metrics_path: /metrics


